### ISSUE TITLE
Solbuild seperates lib32 into another package

### ISSUE THREAD

**Issue by gkr09** [solus-project/solbuild#17]
Hi !
I was building a package that contains certain binary blobs that needs to be present in /usr/lib32
But when building, solbuild **seperates the lib32 folder** into another package (packagename-32bit)
Anyway to change this behaviour ? 
Thanks !

**Comment by ikeydoherty** [comment]
This isn't a solbuild issue its a ypkg one. By default `-32bit` is split out. You can use `patterns` to override that behavior.

i.e.:

```
patterns:
    - /usr/lib32
```

**Comment by gkr09** [comment]
Thank You !

**Comment by ikeydoherty** [comment]
np :)
