### ISSUE TITLE
Feature Request Speed/ETA on source download

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/solbuild#2]
As topic says, speed/eta on source download to provide better information.

**Comment by ikeydoherty** [comment]
Further, we should stop using invoking `curl` and use Go APIs

**Comment by Justinzobel** [comment]
Sounds good to me!

**Comment by ikeydoherty** [comment]
Implemented :) In future I may use a slightly better (colourful) progressbar format but for now it certainly achieves the goals.

![screenshot from 2016-12-10 01-33-51](https://cloud.githubusercontent.com/assets/164489/21070132/cf51d1f2-be78-11e6-9a24-529a27255fc7.png)

**Comment by ikeydoherty** [comment]
Merged into master, will be in the next release
