### ISSUE TITLE
Feature Request: Cache Deletion Command

### ISSUE THREAD

**Issue by JoshStrobl** [solus-project/solbuild#3]
Currently, the process for deleting old solbuild caches involves two separate commands:

- `sudo rm -rf /var/cache/solbuild/profilename/*`
- `sudo rm -rf /var/lib/solbuild/{ccache,packages,sources}/*`

Where `profilename` is main or unstable, obviously.

It'd be great if there was a `delete-cache` command that wiped out the appropriate caches. Makes it a bit easier for maintenance.

**Comment by ikeydoherty** [comment]
Tada. :)
